### PR TITLE
enabling qcqpmodel tests doesn't produce errors

### PR DESCRIPTION
**Pull request by fserra**
this needs https://github.com/leethargo/CSIP/pull/21

### CODE REVIEW

**Comment by leethargo** [comment]
That was easy :smile:

**Comment by fserra** [comment]
why did the test pass? it is using the CSIP version without the `setQuadObj` function...

**Comment by leethargo** [comment]
Maybe there was some old `.so` file being used?

When I try to run the tests with CSIP from `master` branch, there's plenty of errors of this kind:

```
ccall: could not find function CSIPsetQuadObj in library /home/bzfschwa/src/CSIP/lib/libcsip.so
in setquadobjterms! at /home/bzfschwa/.julia/v0.4/SCIP/src/mpb_interface.jl:221
in addQuadratics at /home/bzfschwa/.julia/v0.4/JuMP/src/solvers.jl:444
```

**Comment by leethargo** [comment]
The same kind of errors also occur in Travis, but `FactCheck` seems to eat them all and in the end prints `INFO: SCIP tests passed`, which is why we get the green checkmark.

@mlubin: do you know about this issue with FactCheck and can deal with it?

**Comment by leethargo** [comment]
Instead of using leethargo/CSIP#21, we could also use leethargo/CSIP#22 (after modification).

**Comment by mlubin** [comment]
Looks like the tests are missing a statement like [this](https://github.com/JuliaOpt/JuMP.jl/blob/6fba39ae58963a2dcb20b29001f83d01c9e575ad/test/runtests.jl#L41)

**Pull request merged**
