### PR TITLE
support nonlinear models

### PR DESCRIPTION
**Pull request by fserra**
will work once https://github.com/leethargo/CSIP/pull/22 is accepted

### CODE REVIEW

**Comment by fserra** [comment]
@mlubin Hey!  
can you please modify test/nonlinear.jl in JuMP so that `SCIPSolver` doesn't get call on the `ifelse` test.

**Comment by mlubin** [comment]
@fserra, I'd recommend not testing SCIP as an NLP solver but just as a MINLP solver.

**Comment by fserra** [comment]
ok! then I think we pass all tests :)

**Comment by leethargo** [comment]
I just rebased on master.

**Comment by leethargo** [comment]
Fails on Julia 0.5 with this
```
ERROR: LoadError: LoadError: MethodError: no method matching expr_to_csip(::Symbol, ::Array{Float64,1}, ::Array{SCIP.CSIPNodeData,1})
Closest candidates are:
  expr_to_csip(!Matched::Expr, ::Any, ::Any) at /home/travis/.julia/v0.5/SCIP/src/mpb_interface.jl:458
  expr_to_csip(!Matched::Number, ::Any, ::Any) at /home/travis/.julia/v0.5/SCIP/src/mpb_interface.jl:480

 in constr_expr_to_nodedata(::Expr) at /home/travis/.julia/v0.5/SCIP/src/mpb_interface.jl:444
 in loadproblem!(::SCIP.SCIPMathProgModel, ::Int64, ::Int64, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Symbol, ::JuMP.NLPEvaluator) at /home/travis/.julia/v0.5/SCIP/src/mpb_interface.jl:503
[...]
while loading /home/travis/.julia/v0.5/JuMP/test/nonlinear.jl, in expression starting on line 290
```

**Comment by mlubin** [comment]
@leethargo, yes, the representation of comparisons changed from 0.4 to 0.5. You can use this code to normalize the objects: https://github.com/JuliaOpt/JuMP.jl/blob/25559555f3917d42856db6cad603a3948b7edce5/src/macros.jl#L11

**Comment by leethargo** [comment]
:frowning:

**Pull request merged**
